// Generated by FlutterFire CLI — do not edit manually.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run: flutterfire configure',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not yet configured. '
          'Add GoogleService-Info.plist and re-run: flutterfire configure',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not yet configured. Run: flutterfire configure',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not yet configured. Run: flutterfire configure',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Android ────────────────────────────────────────────────────────────────
  // Source: android/app/google-services.json
  // Project: cashledger-9e954 · Package: com.cashledger.app
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpnehLsIWIcQSGrT4fjW9AE3J37Qx9LHQ',
    appId: '1:1037419082747:android:88e526c10a359de263d15e',
    messagingSenderId: '1037419082747',
    projectId: 'cashledger-9e954',
    storageBucket: 'cashledger-9e954.firebasestorage.app',
  );
}
